package the.spring.cloud.biz.entity.test;

public class TransTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_test.id
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_test.name
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_test.id
     *
     * @return the value of trans_test.id
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_test.id
     *
     * @param id the value for trans_test.id
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_test.name
     *
     * @return the value of trans_test.name
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_test.name
     *
     * @param name the value for trans_test.name
     *
     * @mbggenerated Wed Jul 11 21:13:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}