version: '2.1'

services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
  mongodb:
    image: mongo:6.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - /data/mongo_data:/data/db