package the.spring.cloud.biz.entity;

import java.math.BigDecimal;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.brand_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.title
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.price_market
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private BigDecimal priceMarket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.price_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private BigDecimal priceMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.stock
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.selling
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Byte selling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.shelves
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean shelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.class_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.recommend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.d_integral
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer dIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.code
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.top
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.season_hot
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean seasonHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.restrictions
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Byte restrictions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.description
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.group_buy
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean groupBuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.update_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.create_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.goods_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.latest_promotion
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer latestPromotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.sort
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.p_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.status
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.comment_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer commentMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.sales_sum
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer salesSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.attr_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer attrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.extend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.advance_date
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer advanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.weight
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.area_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_goods.price_vip
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    private Integer priceVip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.id
     *
     * @return the value of db_goods.id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.id
     *
     * @param id the value for db_goods.id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.brand_id
     *
     * @return the value of db_goods.brand_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.brand_id
     *
     * @param brandId the value for db_goods.brand_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.title
     *
     * @return the value of db_goods.title
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.title
     *
     * @param title the value for db_goods.title
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.price_market
     *
     * @return the value of db_goods.price_market
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public BigDecimal getPriceMarket() {
        return priceMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.price_market
     *
     * @param priceMarket the value for db_goods.price_market
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setPriceMarket(BigDecimal priceMarket) {
        this.priceMarket = priceMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.price_member
     *
     * @return the value of db_goods.price_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public BigDecimal getPriceMember() {
        return priceMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.price_member
     *
     * @param priceMember the value for db_goods.price_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setPriceMember(BigDecimal priceMember) {
        this.priceMember = priceMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.stock
     *
     * @return the value of db_goods.stock
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.stock
     *
     * @param stock the value for db_goods.stock
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.selling
     *
     * @return the value of db_goods.selling
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Byte getSelling() {
        return selling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.selling
     *
     * @param selling the value for db_goods.selling
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setSelling(Byte selling) {
        this.selling = selling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.shelves
     *
     * @return the value of db_goods.shelves
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getShelves() {
        return shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.shelves
     *
     * @param shelves the value for db_goods.shelves
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setShelves(Boolean shelves) {
        this.shelves = shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.class_id
     *
     * @return the value of db_goods.class_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.class_id
     *
     * @param classId the value for db_goods.class_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.recommend
     *
     * @return the value of db_goods.recommend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.recommend
     *
     * @param recommend the value for db_goods.recommend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.d_integral
     *
     * @return the value of db_goods.d_integral
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getdIntegral() {
        return dIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.d_integral
     *
     * @param dIntegral the value for db_goods.d_integral
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setdIntegral(Integer dIntegral) {
        this.dIntegral = dIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.code
     *
     * @return the value of db_goods.code
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.code
     *
     * @param code the value for db_goods.code
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.top
     *
     * @return the value of db_goods.top
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.top
     *
     * @param top the value for db_goods.top
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.season_hot
     *
     * @return the value of db_goods.season_hot
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getSeasonHot() {
        return seasonHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.season_hot
     *
     * @param seasonHot the value for db_goods.season_hot
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setSeasonHot(Boolean seasonHot) {
        this.seasonHot = seasonHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.restrictions
     *
     * @return the value of db_goods.restrictions
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Byte getRestrictions() {
        return restrictions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.restrictions
     *
     * @param restrictions the value for db_goods.restrictions
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setRestrictions(Byte restrictions) {
        this.restrictions = restrictions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.description
     *
     * @return the value of db_goods.description
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.description
     *
     * @param description the value for db_goods.description
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.group_buy
     *
     * @return the value of db_goods.group_buy
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getGroupBuy() {
        return groupBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.group_buy
     *
     * @param groupBuy the value for db_goods.group_buy
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setGroupBuy(Boolean groupBuy) {
        this.groupBuy = groupBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.update_time
     *
     * @return the value of db_goods.update_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.update_time
     *
     * @param updateTime the value for db_goods.update_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.create_time
     *
     * @return the value of db_goods.create_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.create_time
     *
     * @param createTime the value for db_goods.create_time
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.goods_type
     *
     * @return the value of db_goods.goods_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.goods_type
     *
     * @param goodsType the value for db_goods.goods_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.latest_promotion
     *
     * @return the value of db_goods.latest_promotion
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getLatestPromotion() {
        return latestPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.latest_promotion
     *
     * @param latestPromotion the value for db_goods.latest_promotion
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setLatestPromotion(Integer latestPromotion) {
        this.latestPromotion = latestPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.sort
     *
     * @return the value of db_goods.sort
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.sort
     *
     * @param sort the value for db_goods.sort
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.p_id
     *
     * @return the value of db_goods.p_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.p_id
     *
     * @param pId the value for db_goods.p_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.status
     *
     * @return the value of db_goods.status
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.status
     *
     * @param status the value for db_goods.status
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.comment_member
     *
     * @return the value of db_goods.comment_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getCommentMember() {
        return commentMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.comment_member
     *
     * @param commentMember the value for db_goods.comment_member
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setCommentMember(Integer commentMember) {
        this.commentMember = commentMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.sales_sum
     *
     * @return the value of db_goods.sales_sum
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getSalesSum() {
        return salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.sales_sum
     *
     * @param salesSum the value for db_goods.sales_sum
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setSalesSum(Integer salesSum) {
        this.salesSum = salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.attr_type
     *
     * @return the value of db_goods.attr_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.attr_type
     *
     * @param attrType the value for db_goods.attr_type
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setAttrType(Integer attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.extend
     *
     * @return the value of db_goods.extend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.extend
     *
     * @param extend the value for db_goods.extend
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setExtend(Integer extend) {
        this.extend = extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.advance_date
     *
     * @return the value of db_goods.advance_date
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getAdvanceDate() {
        return advanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.advance_date
     *
     * @param advanceDate the value for db_goods.advance_date
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setAdvanceDate(Integer advanceDate) {
        this.advanceDate = advanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.weight
     *
     * @return the value of db_goods.weight
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.weight
     *
     * @param weight the value for db_goods.weight
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.area_id
     *
     * @return the value of db_goods.area_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.area_id
     *
     * @param areaId the value for db_goods.area_id
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_goods.price_vip
     *
     * @return the value of db_goods.price_vip
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public Integer getPriceVip() {
        return priceVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_goods.price_vip
     *
     * @param priceVip the value for db_goods.price_vip
     *
     * @mbggenerated Mon Apr 02 09:13:55 CST 2018
     */
    public void setPriceVip(Integer priceVip) {
        this.priceVip = priceVip;
    }
}